[project]
name = "src"
version = "0.0.1"
description = "MLOps"
authors = [{name = "Prince Khunt"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}